// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

package dic

import (
	"dou-survey/app/controller"
	"dou-survey/app/repository"
	"dou-survey/app/service"
	"dou-survey/internal/logger"
	"dou-survey/internal/storage"
)

// Injectors from wire.go:

// User
func InitUserRepository(db *storage.DbStore) repository.UserRepositoryInterface {
	userRepositoryInterface := repository.NewUserRepository(db)
	return userRepositoryInterface
}

func InitUserService(userRepo repository.UserRepositoryInterface) service.UserServiceInterface {
	userServiceInterface := service.NewUserService(userRepo)
	return userServiceInterface
}

func InitUserController(us service.UserServiceInterface, logger2 logger.Logger) controller.UserControllerInterface {
	userControllerInterface := controller.NewUserController(us, logger2)
	return userControllerInterface
}

// Auth
func InitAuthService(userRepo repository.UserRepositoryInterface, logger2 logger.Logger) service.AuthServiceInterface {
	authServiceInterface := service.NewAuthService(userRepo, logger2)
	return authServiceInterface
}

func InitAuthController(as service.AuthServiceInterface, us service.UserServiceInterface, logger2 logger.Logger) controller.AuthControllerInterface {
	authControllerInterface := controller.NewAuthController(as, us, logger2)
	return authControllerInterface
}

// Employee
func InitEmployeeRepository(db *storage.DbStore) repository.EmployeeRepositoryInterface {
	employeeRepositoryInterface := repository.NewEmployeeRepository(db)
	return employeeRepositoryInterface
}

func InitEmployeeService(employeeRepo repository.EmployeeRepositoryInterface) service.EmployeeServiceInterface {
	employeeServiceInterface := service.NewEmployeeService(employeeRepo)
	return employeeServiceInterface
}

func InitEmployeeController(us service.EmployeeServiceInterface, logger2 logger.Logger) controller.EmployeeControllerInterface {
	employeeControllerInterface := controller.NewEmployeeController(us, logger2)
	return employeeControllerInterface
}

// Survey
func InitSurveyRepository(db *storage.DbStore, logger2 logger.Logger) repository.SurveyRepositoryInterface {
	surveyRepositoryInterface := repository.NewSurveyRepository(db, logger2)
	return surveyRepositoryInterface
}

func InitSurveyService(surveyRepo repository.SurveyRepositoryInterface) service.SurveyServiceInterface {
	surveyServiceInterface := service.NewSurveyService(surveyRepo)
	return surveyServiceInterface
}

func InitSurveyController(ss service.SurveyServiceInterface, us service.UserServiceInterface, logger2 logger.Logger) controller.SurveyControllerInterface {
	surveyControllerInterface := controller.NewSurveyController(ss, us, logger2)
	return surveyControllerInterface
}
