// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire

package dic

import (
	"dou-survey/app/controller/authController"
	"dou-survey/app/controller/employeeController"
	"dou-survey/app/controller/userController"
	"dou-survey/app/repository/employeeRepository"
	"dou-survey/app/repository/userRepository"
	"dou-survey/app/service/authService"
	"dou-survey/app/service/employeeService"
	"dou-survey/app/service/userService"
	"dou-survey/internal/logger"
	"dou-survey/internal/storage"
)

// Injectors from wire.go:

// User
func InitUserRepository(db *storage.DbStore) userRepository.UserRepositoryInterface {
	userRepositoryInterface := userRepository.NewUserRepository(db)
	return userRepositoryInterface
}

func InitUserService(userRepo userRepository.UserRepositoryInterface) userService.UserServiceInterface {
	userServiceInterface := userService.NewUserService(userRepo)
	return userServiceInterface
}

func InitUserController(us userService.UserServiceInterface, logger2 logger.Logger) userController.UserControllerInterface {
	userControllerInterface := userController.NewUserController(us, logger2)
	return userControllerInterface
}

// Auth
func InitAuthService(userRepo userRepository.UserRepositoryInterface, logger2 logger.Logger) authService.AuthServiceInterface {
	authServiceInterface := authService.NewAuthService(userRepo, logger2)
	return authServiceInterface
}

func InitAuthController(us authService.AuthServiceInterface, logger2 logger.Logger) authController.AuthControllerInterface {
	authControllerInterface := authController.NewAuthController(us, logger2)
	return authControllerInterface
}

// Employee
func InitEmployeeRepository(db *storage.DbStore) employeeRepository.EmployeeRepositoryInterface {
	employeeRepositoryInterface := employeeRepository.NewEmployeeRepository(db)
	return employeeRepositoryInterface
}

func InitEmployeeService(employeeRepo employeeRepository.EmployeeRepositoryInterface) employeeService.EmployeeServiceInterface {
	employeeServiceInterface := employeeService.NewEmployeeService(employeeRepo)
	return employeeServiceInterface
}

func InitEmployeeController(us employeeService.EmployeeServiceInterface, logger2 logger.Logger) employeeController.EmployeeControllerInterface {
	employeeControllerInterface := employeeController.NewEmployeeController(us, logger2)
	return employeeControllerInterface
}
